stages:
  - build
  - deploy

build donald:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - donald
  script:
    - npm install
    - npm run build

deploy donald:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - donald
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/. ~/front-deployment

deploy dev-donald:
  stage: deploy
  only:
    refs:
      - feature/login-page
  tags:
    - donald
  script:
    - mkdir -p ~/dev-front-deployment
    - rm -rf ~/dev-front-deployment/*
    - cp -r dist/. ~/dev-front-deployment
